apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}
  labels: {{- include "nginx.labels" . | nindent 4 }}
data:
  default.conf:
    {{ toYaml .Values.configData | indent 4 | trim }}
{{- range $key, $value := .Values.extraFiles }}
  {{ $key }}:
    {{ toYaml $value | indent 4 | trim }}
{{- end }}
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Nginx {{ .Values.env }}</title>
    </head>
    <body>
    Environment : <strong>{{ .Values.env }}</strong>
    </body>
    </html>

